right_format = "$time"
command_timeout=5000

format = """
[┌─](bold bright-black) $directory$git_branch$git_status$nodejs$python$java$lua$rust$package$cmd_duration$custom$status
[└─](bold bright-black)$character"""

[directory]
truncation_length = 3
truncate_to_repo = true
style = "cyan"
repo_root_style = "bold purple"
read_only = " "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_status]
staged = '+${count}'
modified = '!${count}'
deleted = '✘${count}'
renamed = '»${count}'
untracked = '?${count}'
conflicted = '=${count}'
stashed = '\$${count}'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'

[cmd_duration]
min_time = 200
format = "took [$duration](bold yellow) "

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[status]
disabled = false
symbol = "✗"
style = "bold red"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style) '
map_symbol = true

[character]
success_symbol = "[➤](bold green)"
error_symbol = "[➤](bold red)"

# [line_break]
# disabled = true

[custom.sf]
description = "Salesforce target org"
detect_files = ["sfdx-project.json"]
symbol = "☁ "
style = "bold bright-blue"
command = "starship-sf-org"
format = "using [$symbol$output ](bright-blue)"
